using Crayons
function print_help()
    print(Crayon(foreground = :white),"\nSearch files using the full file name or only the extension using the flag [-s]\n\n")
    print(Crayon(foreground = :white),"\nCommands: \n\t")
    print(Crayon(foreground = :light_green), "-> help [-h]\n\t")
    print(Crayon(foreground = :light_green), "-> search [-s]\n\t")
    print(Crayon(foreground = :light_green), "-> compare [-c]\n\t")
    print(Crayon(foreground = :white),"\nUsage: ", Crayon(foreground = :light_green), "julia src/FileCLI.jl -s path ext1 ext2 ext3\n\n")
    print(Crayon(foreground = :white),"---------------------------------\n")
    print(Crayon(foreground = :white),"             Search              \n")
    print(Crayon(foreground = :white),"---------------------------------\n")
    print(Crayon(foreground = :white),"- To search for .jl files in the CURRENT directory\n\nRun: \t", Crayon(foreground = :light_green), "julia src/FileCLI.jl -s . jl\n\n")
    print(Crayon(foreground = :white),"- To search for .jl files in the PARENT directory\n\nRun: \t", Crayon(foreground = :light_green), "julia src/FileCLI.jl -s ../ jl\n\n")
    print(Crayon(foreground = :white),"- To search for a files called package.json in the PARENT directory\n\nRun: \t", Crayon(foreground = :light_green), "julia src/FileCLI.jl -s ../ package.json\n\n")
    print(Crayon(foreground = :white),"----------------------------------\n")
    print(Crayon(foreground = :white),"             Compare              \n")
    print(Crayon(foreground = :white),"----------------------------------\n")
    print(Crayon(foreground = :white),"- To compare two files\n\nRun: \t", Crayon(foreground = :light_green), "julia src/FileCLI.jl -c file1 file2\n\n")
end